name: 'nix-shell(2)'
description: 'nix-shell instead of nix run'
author: '@workflow and @ZenithalHourlyRate and @dx-oss'
inputs:
  interpreter:
    required: true
    description: 'Interpreter to use in the nix shell shebang'
    default: 'bash'
  file:
    required: true
    description: 'nix shell file'
    default: 'shell.nix'
  script:
    required: true
    description: 'The actual script to execute in the shell'
branding:
  color: 'blue'
  icon: 'chevron-right'
runs:
  using: 'node12'
  main: 'lib/main.js'
